SET search_path TO playstation_rental;

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ORDER_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'COURIER_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ORDER_ARRIVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ADMIN_ORDER_ASSIGNED';
