SET search_path TO playstation_rental;

ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'COURIER_ASSIGNED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'ARRIVED';

ALTER TABLE users ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS username TEXT;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS "depositAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS "acceptedAt" TIMESTAMP(3);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS "assignedAt" TIMESTAMP(3);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS "deliveryStartedAt" TIMESTAMP(3);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS "deliveryCompletedAt" TIMESTAMP(3);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS "assignedByAdmin" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE order_status_logs ADD COLUMN IF NOT EXISTS "actorType" TEXT;
ALTER TABLE order_status_logs ADD COLUMN IF NOT EXISTS "actorId" INTEGER;
ALTER TABLE order_status_logs ADD COLUMN IF NOT EXISTS note TEXT;
